name: Manual Trigger

# 手动触发事件
on: workflow_dispatch

jobs:
  publish-code:
    runs-on: ubuntu-latest
    steps:
    - name: setup aliyun oss
      uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: "oss-cn-hangzhou.aliyuncs.com"
        access-key-id: ${{ secrets.KEY }}
        access-key-secret: ${{ secrets.SECRET }}
    - name: cp files to master
      run: ossutil cp -rf oss://tudou233/stable/ oss://tudou233/master/
