name: Manual Trigger

on:
  # 手动触发事件
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: setup aliyun oss
      uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: "oss-cn-hangzhou.aliyuncs.com"
        access-key-id: ${{ secrets.KEY }}
        access-key-secret: ${{ secrets.SECRET }}
    - name: cp files to aliyun
      run: ossutil cp -rf oss://tudou233/stable/ oss://tudou233/master/
